In [1]:
import numpy as np

In [2]:
particle_size = 3
disk_size = int(particle_size/2) 
crop_size = int(particle_size/2) *2


print('disk',disk_size, ' crop ', crop_size)

y_pos = 12
x_pos = 8


disk 1  crop  2


In [3]:
image = np.ones((50,50))*2

image = image//2
image[y_pos-(disk_size):y_pos+(disk_size+1), x_pos-(disk_size):x_pos+(disk_size+1)] = 2

print('original image')
print(image)


original image
[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]


In [4]:
recentered_image_donut = image.copy().astype(np.float32)
crop_image = recentered_image_donut[y_pos-(crop_size):y_pos+(crop_size+1), x_pos-(crop_size):x_pos+(crop_size+1)]
center_coordinates = int(crop_image.shape[0]/2)

print('crop')
print(crop_image)

print( np.mean(crop_image[center_coordinates-(disk_size):center_coordinates+(disk_size+1), center_coordinates-(disk_size):center_coordinates+(disk_size+1)].flatten()) )


crop
[[1. 1. 1. 1. 1.]
 [1. 2. 2. 2. 1.]
 [1. 2. 2. 2. 1.]
 [1. 2. 2. 2. 1.]
 [1. 1. 1. 1. 1.]]
2.0


In [5]:

crop_image[center_coordinates-disk_size:center_coordinates+disk_size+1, center_coordinates-disk_size:center_coordinates+disk_size+1] = np.nan
print('image_in_disk')
print(crop_image)

image_in_disk
[[ 1.  1.  1.  1.  1.]
 [ 1. nan nan nan  1.]
 [ 1. nan nan nan  1.]
 [ 1. nan nan nan  1.]
 [ 1.  1.  1.  1.  1.]]


In [6]:
print( np.nanmean(crop_image.flatten()) )

1.0
